ekf_filter_node:
  ros__parameters:  # This is the required key in ROS 2
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    imu0: /livox/imu
    imu0_config: [false, false, false,  # x, y, z (position)
                  false, false, false,  # Roll, Pitch, Yaw (orientation)
                  false, false, false,   # x, y, z (velocity)
                  false, false, true,  # Angular velocity in x, y, z
                  true, true, false]  # Linear acceleration (if not used, make false)
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
    imu0_nodelay: false
    imu0_relative: true
    imu0_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
    imu0_twist_rejection_threshold: 0.8                #
    imu0_linear_acceleration_rejection_threshold: 0.8 
    imu0_remove_gravitational_acceleration: true
    imu0_queue_size: 5
    imu0_covariance: [0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00,
                      0.00, 0.00, 0.00]
